version: "3.4"
services:
    media-postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    media:
        image: openslides-media-dev
        environment:
            - MEDIA_DATABASE_HOST=media-postgresql
            - MEDIA_DATABASE_PORT=5432
            - MEDIA_DATABASE_NAME=openslides
            - MEDIA_DATABASE_USER_FILE=/run/secrets/media_database_user
            - MEDIA_DATABASE_PASSWORD_FILE=/run/secrets/media_database_password
            - PRESENTER_HOST=dummy_presenter
            - PRESENTER_PORT=9003
            - MEDIA_ENABLE_DEV_ENVIRONMENT=1
        volumes:
            - ./src:/app/src
        ports:
            - 9006:9006
    dummy_presenter:
        image: openslides-media-dummy-presenter
        volumes:
            - ./tests/dummy_presenter:/app/dummy_presenter
    tests:
        image: openslides-media-tests
        depends_on:
            - media
            - media-postgresql
            - dummy_presenter
        volumes:
            - ./tests:/app/tests
